# -*- coding: utf-8 -*-
"""予測＿企業２.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rmPQivVarxnUcBf9CK__LHRGmGPaJVnz
"""

from tensorflow.python.keras.applications.vgg16 import preprocess_input,decode_predictions
from tensorflow.python.keras.preprocessing.image import load_img,img_to_array
import numpy as np
import pandas as pd
import os, glob
from tensorflow.keras.models import load_model
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_Puppy = ["./drive/My Drive/dataset/2/Puppy"]

#写真の取り出し
Y = []
images = []
for name in folder_Puppy:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("Puppy2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_Teddy_Bear = ["./drive/My Drive/dataset/2/Teddy Bear"]

#写真の取り出し
Y = []
images = []
for name in folder_Teddy_Bear:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("Teddy Bear2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_Muffin = ["./drive/My Drive/dataset/2/Muffin"]

#写真の取り出し
Y = []
images = []
for name in folder_Muffin:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("Muffin2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_Labradoodle = ["./drive/My Drive/dataset/2/Labradoodle"]

#写真の取り出し
Y = []
images = []
for name in folder_Labradoodle:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("Labradoodle2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_Afghan_Hound = ["./drive/My Drive/dataset/2/Afghan Hound"]

#写真の取り出し
Y = []
images = []
for name in folder_Afghan_Hound:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("Afghan Hound2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_chihuahua = ["./drive/My Drive/dataset/2/chihuahua"]

#写真の取り出し
Y = []
images = []
for name in folder_chihuahua:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("chihuahua2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_cookie = ["./drive/My Drive/dataset/2/cookie"]

#写真の取り出し
Y = []
images = []
for name in folder_cookie:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("cookie2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_Fried_Chicken = ["./drive/My Drive/dataset/2/Fried Chicken"]

#写真の取り出し
Y = []
images = []
for name in folder_Fried_Chicken:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("Fried Chicken2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_Mop = ["./drive/My Drive/dataset/2/Mop"]

#写真の取り出し
Y = []
images = []
for name in folder_Mop:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("Mop2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_Saruman = ["./drive/My Drive/dataset/2/Saruman"]

#写真の取り出し
Y = []
images = []
for name in folder_Saruman:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("Saruman2.csv",index = False)

model = load_model('./drive/My Drive/AI画像分類ハッカソン /h5/sample01.h5')

images=[]
Y=[]
folder_Sheepdog = ["./drive/My Drive/dataset/2/Sheepdog"]

#写真の取り出し
Y = []
images = []
for name in folder_Sheepdog:
    path = glob.glob(name + '/*.*') 
    for img in path:
        Y.append(img)
        images.append(preprocess_input(img_to_array(load_img(img, target_size=(224, 224)))))
len(images)


preds = model.predict(np.stack(images))
classes = ['Afghan Hound','chihuahua','cookie','Fried Chicken','Labradoodle','Mop','Muffin','Puppy','Saruman','Sheepdog','Teddy Bear']
pred_labels = np.argmax(preds, axis=-1)

pred_label_names = [classes[x] for x in pred_labels]
print(pred_label_names)  

resuls=[]
#for i in range(292):
 #   resuls.append(pred_label_names[i])

resuls = pd.DataFrame(pred_label_names,columns=["class"])
Y = pd.DataFrame(Y,columns=["index"])

index= pd.concat([Y,resuls],axis=1)
index.to_csv("Sheepdog2.csv",index = False)

