# -*- coding: utf-8 -*-
"""企業２_精度.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vKUVnfUvDmniBagujiWNJJPHOkv45nd1
"""

import pandas as pd

Afghan_Hound = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/Afghan Hound2.csv')
df_bool = Afghan_Hound['class'] == 'Afghan Hound'
num = len(Afghan_Hound)
print("Afghan_Hound:" + str(df_bool.sum()) + '/' + str(num))

Fried_Chicken = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/Fried Chicken2.csv')
 df_bool = Fried_Chicken['class'] == 'Fried Chicken'
num = len(Fried_Chicken)
print('Fried Chicken:' + str(df_bool.sum()) + '/' + str(num))

Labradoodle = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/Labradoodle2.csv')
df_bool = Labradoodle['class'] == 'Labradoodle'
num = len(Labradoodle)
print('Labradoodle:' + str(df_bool.sum()) + '/' + str(num))

Mop = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/Mop2.csv')
df_bool = Mop['class'] == 'Mop'
num = len(Mop)
print('Mop:' + str(df_bool.sum()) + '/' + str(num))

Muffin = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/Muffin2.csv')
df_bool = Muffin['class'] == 'Muffin'
num = len(Muffin)
print('Muffin:' + str(df_bool.sum()) + '/' + str(num))

Puppy = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/Puppy2.csv')
df_bool = Puppy['class'] == 'Puppy'
num = len(Puppy)
print('Puppy:' + str(df_bool.sum()) + '/' + str(num))

Saruman = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/Saruman2.csv')
df_bool = Saruman['class'] == 'Saruman'
num = len(Saruman)
print('Saruman:' + str(df_bool.sum()) + '/' + str(num))

Sheepdog = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/Sheepdog2.csv')
df_bool = Sheepdog['class'] == 'Sheepdog'
num = len(Sheepdog)
print('Sheepdog:' + str(df_bool.sum()) + '/' + str(num))

Teddy_Bear = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/Teddy Bear2.csv')
df_bool = Teddy_Bear['class'] == 'Teddy Bear'
num = len(Teddy_Bear)
print('Teddy Bear:' + str(df_bool.sum()) + '/' + str(num))

chihuahua = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/chihuahua2.csv')
df_bool = chihuahua['class'] == 'chihuahua'
num = len(chihuahua)
print('chihuahua:' + str(df_bool.sum()) + '/' + str(num))

cookie = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業2/cookie2.csv')
df_bool = cookie['class'] == 'cookie'
num = len(cookie)
print('cookie:' + str(df_bool.sum()) + '/' + str(num))

