# -*- coding: utf-8 -*-
"""企業１_精度.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JdrSSwLEzrJozrQLcVmKoyXuHdUGI9BL
"""

import pandas as pd

Afghan_Hound = pd.read_csv('./drive/My Drive/AI画像分類ハッカソン /企業１/Afghan Hound1.csv')
df_bool = Afghan_Hound['class'] == 'Afghan Hound'
num = len(Afghan_Hound)
print("Afghan_Hound:" + str(df_bool.sum()) + '/' + str(num))

Fried_Chicken = pd.read_csv('./drive/My Drive/AI画像分類ハッカソン /企業１/Fried Chicken1.csv')
 df_bool = Fried_Chicken['class'] == 'Fried Chicken'
num = len(Fried_Chicken)
print('Fried Chicken:' + str(df_bool.sum()) + '/' + str(num))

Labradoodle = pd.read_csv('./drive/My Drive/AI画像分類ハッカソン /企業１/Labradoodle1.csv')
df_bool = Labradoodle['class'] == 'Labradoodle'
num = len(Labradoodle)
print('Labradoodle:' + str(df_bool.sum()) + '/' + str(num))

Mop = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業１/Mop1.csv')
df_bool = Mop['class'] == 'Mop'
num = len(Mop)
print('Mop:' + str(df_bool.sum()) + '/' + str(num))

Muffin = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業１/Muffin1.csv')
df_bool = Muffin['class'] == 'Muffin'
num = len(Muffin)
print('Muffin:' + str(df_bool.sum()) + '/' + str(num))

Puppy = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業１/Puppy1.csv')
df_bool = Puppy['class'] == 'Puppy'
num = len(Puppy)
print('Puppy:' + str(df_bool.sum()) + '/' + str(num))

Saruman = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業１/Saruman1.csv')
df_bool = Saruman['class'] == 'Saruman'
num = len(Saruman)
print('Saruman:' + str(df_bool.sum()) + '/' + str(num))

Sheepdog = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業１/Sheepdog1.csv')
df_bool = Sheepdog['class'] == 'Sheepdog'
num = len(Sheepdog)
print('Sheepdog:' + str(df_bool.sum()) + '/' + str(num))

Teddy_Bear = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業１/Teddy Bear1.csv')
df_bool = Teddy_Bear['class'] == 'Teddy Bear'
num = len(Teddy_Bear)
print('Teddy Bear:' + str(df_bool.sum()) + '/' + str(num))

chihuahua = pd.read_csv('./drive/My Drive/AI画像分類ハッカソン /企業１/chihuahua1.csv')
df_bool = chihuahua['class'] == 'chihuahua'
num = len(chihuahua)
print('chihuahua:' + str(df_bool.sum()) + '/' + str(num))

cookie = pd.read_csv('/content/drive/My Drive/AI画像分類ハッカソン /企業１/cookie1.csv')
df_bool = cookie['class'] == 'cookie'
num = len(cookie)
print('cookie:' + str(df_bool.sum()) + '/' + str(num))

